name: attendly
description: "A new Flutter project."
publish_to: 'none'
version: 1.4.1+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.8.3
  permission_handler: ^12.0.1
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.5
  fl_chart: ^1.0.0
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  open_filex: ^4.5.0
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.4
  flutter_markdown_plus: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/attendly_docs.pdf
    - assets/changelogs/